name: "[ddip] Pull Request"

description: "기능 개발, 버그 수정 등을 위한 PR 템플릿입니다."

body:
  - type: textarea
    id: summary
    attributes:
      label: "📝 작업 내용 요약"
      description: "이번 PR의 핵심 내용을 작성해주세요."
      placeholder: "예: 로그인 API 버그 수정 및 관련 테스트 코드 추가"
    validations:
      required: true

  - type: textarea
    id: issue-number
    attributes:
      label: "🔗 관련 이슈 번호"
      description: "이 PR과 관련된 이슈가 있다면 'Closes #이슈번호' 형식으로 작성해주세요. 여러 개일 경우 쉼표로 구분합니다."
      placeholder: "예: Closes #123, Fixes #456"
    validations:
      required: false
